<?php

namespace VictorStochero\Warden\Console\Demo;

use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Minimal mail notification emitted by warden:demo so that NotificationSent
 * (and the underlying MessageSent) fire through the native Laravel path.
 */
class DemoNotification extends Notification
{
    /** @return list<string> */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('Warden demo notification')
            ->line('This notification was generated by warden:demo.');
    }
}
